import express from 'express'; import mongoose from 'mongoose'; import jwt from 'jsonwebtoken';
const router=express.Router();const JWT_SECRET=process.env.JWT_SECRET||'change-me-in-production';
const settingsSchema=new mongoose.Schema({key:{type:String,unique:true,default:'main'},restaurantName:{type:String,default:'THE BAKEST'},tagline:{type:String,default:'Freshly Baked. Beautifully Crafted.'},phone:{type:String,default:'+91 98765 43210'},email:{type:String,default:'hello@thebakest.com'},address:{type:String,default:'272-B, Near Al-Nihar, Jamia Nagar, Okhla, New Delhi'},logoUrl:{type:String,default:''},heroImageUrl:{type:String,default:''},storyImageUrl:{type:String,default:''},restaurantOpen:{type:Boolean,default:true},openingHours:{type:Map,of:String,default:{}},deliveryCharge:{type:Number,default:40},taxRate:{type:Number,default:5},instagram:{type:String,default:''},facebook:{type:String,default:''},twitter:{type:String,default:''}},{timestamps:true});
const StoreSetting=mongoose.models.StoreSetting||mongoose.model('StoreSetting',settingsSchema);const defaults={restaurantName:'THE BAKEST',tagline:'Freshly Baked. Beautifully Crafted.',phone:'+91 98765 43210',email:'hello@thebakest.com',address:'272-B, Near Al-Nihar, Jamia Nagar, Okhla, New Delhi',logoUrl:'',heroImageUrl:'',storyImageUrl:'',restaurantOpen:true,openingHours:{Monday:'11:00 AM - 11:00 PM',Tuesday:'11:00 AM - 11:00 PM',Wednesday:'11:00 AM - 11:00 PM',Thursday:'11:00 AM - 11:00 PM',Friday:'11:00 AM - 12:00 AM',Saturday:'11:00 AM - 12:00 AM',Sunday:'12:00 PM - 11:00 PM'},deliveryCharge:40,taxRate:5,instagram:'https://instagram.com',facebook:'https://facebook.com',twitter:'https://twitter.com'};
const userModel=mongoose.models.CodUser||mongoose.model('CodUser',new mongoose.Schema({codEligible:{type:Boolean,default:false}},{collection:'users',strict:false}));
const orderModel=mongoose.models.CodOrder||mongoose.model('CodOrder',new mongoose.Schema({user_id:mongoose.Schema.Types.ObjectId,payment_method:String,payment_status:String,total:Number,createdAt:Date},{collection:'orders',strict:false,timestamps:false}));
function publicSettings(s){const o=s.toObject();o.id=s._id.toString();delete o._id;const h=s.openingHours;o.openingHours=h instanceof Map?Object.fromEntries(h):{...(h||{})};return o}
async function getSettings(){let s=await StoreSetting.findOne({key:'main'});if(!s)s=await StoreSetting.create({key:'main',...defaults});return s}
function getAuth(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return null;try{return jwt.verify(h.slice(7),JWT_SECRET)}catch{return null}}
function auth(req,res,next){const p=getAuth(req);if(!p)return res.status(401).json({success:false,message:'Authentication required'});req.auth=p;next()}
function admin(req,res,next){const p=getAuth(req);if(!p)return res.status(401).json({success:false,message:'Authentication required'});if(p.role!=='admin')return res.status(403).json({success:false,message:'Admin access required'});req.auth=p;next()}
router.get('/',async(req,res)=>{try{res.json({success:true,message:'Settings loaded',data:publicSettings(await getSettings())})}catch(e){res.status(500).json({success:false,message:e.message})}});
router.put('/',admin,async(req,res)=>{try{const allowed=['restaurantName','tagline','phone','email','address','logoUrl','heroImageUrl','storyImageUrl','restaurantOpen','openingHours','deliveryCharge','taxRate','instagram','facebook','twitter'];const update={};for(const k of allowed)if(req.body[k]!==undefined)update[k]=req.body[k];const s=await StoreSetting.findOneAndUpdate({key:'main'},{$set:{...defaults,...update,key:'main'}},{upsert:true,new:true,setDefaultsOnInsert:true});res.json({success:true,message:'Cafe settings updated',data:publicSettings(s)})}catch(e){res.status(500).json({success:false,message:e.message})}});
router.get('/cod-eligibility/me',auth,async(req,res)=>{try{const user=await userModel.findById(req.auth.id).lean();res.json({success:true,message:'COD eligibility loaded',data:{eligible:user?.codEligible===true}})}catch(e){res.status(500).json({success:false,message:e.message})}});
router.get('/cod-eligibility/customers',admin,async(req,res)=>{try{const users=await userModel.find({role:'customer'}).select('email firstName lastName phone createdAt codEligible').lean();const ids=users.map(u=>u._id);const paid=await orderModel.aggregate([{$match:{user_id:{$in:ids},payment_method:'online',payment_status:'paid'}},{$group:{_id:'$user_id',online_orders:{$sum:1},online_paid:{$sum:'$total'}}}]);const stats=new Map(paid.map(x=>[String(x._id),x]));const data=users.map(u=>{const s=stats.get(String(u._id))||{};return {user_id:String(u._id),first_name:u.firstName||'',last_name:u.lastName||'',phone:u.phone||'',email:u.email||'',order_count:Number(s.online_orders||0),online_paid:Number(s.online_paid||0),cod_eligible:u.codEligible===true,joined_at:u.createdAt}});res.json({success:true,message:'COD customers loaded',data})}catch(e){res.status(500).json({success:false,message:e.message})}});
router.put('/cod-eligibility/:userId',admin,async(req,res)=>{try{if(!mongoose.isValidObjectId(req.params.userId))return res.status(400).json({success:false,message:'Invalid customer'});const eligible=req.body?.eligible===true;const user=await userModel.findOneAndUpdate({_id:req.params.userId,role:'customer'},{$set:{codEligible:eligible}},{new:true});if(!user)return res.status(404).json({success:false,message:'Customer not found'});res.json({success:true,message:eligible?'COD enabled for this customer':'COD disabled for this customer',data:{user_id:String(user._id),eligible:user.codEligible===true}})}catch(e){res.status(500).json({success:false,message:e.message})}});
export default router;
