import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Search, SlidersHorizontal, X } from 'lucide-react';
import { menuApi, categoriesApi } from '@/lib/api';
import type { Category, MenuItem } from '@/lib/types';
import { ProductCard, ProductCardSkeleton } from '@/components/ProductCard';
import { EmptyState } from '@/components/ui';
import { motion } from 'framer-motion';

export default function Menu(){
 const [searchParams,setSearchParams]=useSearchParams();const [categories,setCategories]=useState<Category[]>([]);const [items,setItems]=useState<MenuItem[]>([]);const [loading,setLoading]=useState(true);const [query,setQuery]=useState('');const activeCat=searchParams.get('cat')??'all';
 useEffect(()=>{let active=true;const load=async()=>{const [catRes,itemRes]=await Promise.all([categoriesApi.list(),menuApi.list()]);if(!active)return;setCategories((catRes.data as Category[])??[]);setItems((itemRes.data as MenuItem[])??[]);setLoading(false)};load();const t=window.setInterval(load,8000);return()=>{active=false;window.clearInterval(t)}},[]);
 const setCat=(slug:string)=>slug==='all'?setSearchParams({}):setSearchParams({cat:slug});
 const filtered=useMemo(()=>{let list=items;if(activeCat!=='all'){const cat=categories.find(c=>c.slug===activeCat);if(cat)list=list.filter(i=>i.category_id===cat.id)}if(query.trim()){const q=query.toLowerCase();list=list.filter(i=>i.name.toLowerCase().includes(q)||i.description.toLowerCase().includes(q)||(i.tags??[]).some(t=>t.toLowerCase().includes(q)))}return list},[items,activeCat,categories,query]);
 const grouped=useMemo(()=>{if(activeCat!=='all'){const cat=categories.find(c=>c.slug===activeCat);return cat?[{category:cat,items:filtered}]:[]}return categories.map(c=>({category:c,items:filtered.filter(i=>i.category_id===c.id)})).filter(g=>g.items.length>0)},[filtered,categories,activeCat]);
 useEffect(()=>{if(loading||activeCat==='all')return;const id=window.requestAnimationFrame(()=>{document.getElementById(`category-${activeCat}`)?.scrollIntoView({behavior:'smooth',block:'start'});});return()=>window.cancelAnimationFrame(id)},[activeCat,loading,items.length,categories.length]);
 return <div><section className="border-b border-bakery-primary/10 bg-gradient-to-b from-bakery-sky to-bakery-cream"><div className="container-bk py-12 text-center"><h1 className="font-display text-4xl font-bold text-bakery-ink sm:text-5xl">Our Menu</h1><p className="mx-auto mt-3 max-w-xl text-bakery-ink/60">Sixteen categories of freshly baked treats. Search, filter, and add your favourites to the cart.</p><div className="mx-auto mt-6 max-w-xl relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-bakery-ink/40"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search cakes, pastries, brownies..." className="w-full rounded-full border border-bakery-primary/15 bg-white py-3.5 pl-12 pr-12 text-sm text-bakery-ink placeholder:text-bakery-ink/40 shadow-soft focus:border-bakery-primary focus:outline-none focus:ring-2 focus:ring-bakery-primary/15"/>{query&&<button onClick={()=>setQuery('')} className="absolute right-4 top-1/2 -translate-y-1/2 text-bakery-ink/40 hover:text-bakery-ink/70"><X className="h-4 w-4"/></button>}</div></div></section><div className="sticky top-16 z-30 border-b border-bakery-primary/10 bg-white/90 backdrop-blur-md lg:top-20"><div className="container-bk flex items-center gap-2 py-3 overflow-x-auto no-scrollbar"><span className="hidden items-center gap-1.5 shrink-0 text-xs font-semibold uppercase tracking-wider text-bakery-ink/40 sm:flex"><SlidersHorizontal className="h-3.5 w-3.5"/>Filter:</span><CatPill active={activeCat==='all'} onClick={()=>setCat('all')} label="All"/>{categories.map(c=><CatPill key={c.id} active={activeCat===c.slug} onClick={()=>setCat(c.slug)} label={c.name}/>)}</div></div><section className="container-bk py-10">{loading?<div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{Array.from({length:8}).map((_,i)=><ProductCardSkeleton key={i}/>)}</div>:filtered.length===0?<EmptyState icon={Search} title="No treats found" message="Try a different search or category — we have 100+ baked delights on the menu." actionLabel="Browse all" actionTo="/menu"/>:<div className="space-y-12">{grouped.map(({category,items:catItems})=><div key={category.id} id={`category-${category.slug}`} className="scroll-mt-32"><motion.h2 initial={{opacity:0,x:-10}} whileInView={{opacity:1,x:0}} viewport={{once:true}} className="mb-5 flex items-center gap-3 font-display text-2xl font-bold text-bakery-ink">{category.name}<span className="rounded-full bg-bakery-sky px-2.5 py-0.5 text-xs font-semibold text-bakery-primary">{catItems.length}</span></motion.h2><div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{catItems.map(item=><ProductCard key={item.id} item={item}/>)}</div></div>)}</div>}</section></div>;
}
function CatPill({active,onClick,label}:{active:boolean;onClick:()=>void;label:string}){return <button onClick={onClick} className={`shrink-0 rounded-full px-4 py-1.5 text-sm font-medium transition-all ${active?'bg-bakery-primary text-white shadow-soft':'bg-bakery-sky/60 text-bakery-ink/70 hover:bg-bakery-sky hover:text-bakery-primary'}`}>{label}</button>}
