import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Search, SlidersHorizontal, X } from 'lucide-react';
import { menuApi, categoriesApi } from '@/lib/api';
import type { Category, MenuItem } from '@/lib/types';
import { ProductCard, ProductCardSkeleton } from '@/components/ProductCard';
import { EmptyState } from '@/components/ui';
import { motion } from 'framer-motion';

const slugify=(value:string)=>String(value??'').trim().toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const aliases:Record<string,string[]>={cookies:['cookie','cookies'],cheesecakes:['cheesecake','cheesecakes'],croissants:['croissant','croissants'],'cake-jars':['cake-jar','cake-jars','jar-cakes','jar-cake','jars']};
const itemCategorySlug=(item:MenuItem)=>slugify(item.category?.slug||item.category?.name||(item as any).category_name||'');
const categoryMatches=(category:Category,wanted:string)=>{const a=slugify(category.slug||category.name);const b=slugify(wanted);return a===b||(aliases[a]??[]).includes(b)||(aliases[b]??[]).includes(a)};

export default function Menu(){
 const [searchParams,setSearchParams]=useSearchParams();const [categories,setCategories]=useState<Category[]>([]);const [items,setItems]=useState<MenuItem[]>([]);const [loading,setLoading]=useState(true);const [query,setQuery]=useState('');const activeCat=slugify(searchParams.get('cat')??'all')||'all';
 useEffect(()=>{let active=true;const load=async()=>{const [catRes,itemRes]=await Promise.all([categoriesApi.list(),menuApi.list()]);if(!active)return;setCategories((catRes.data as Category[])??[]);setItems((itemRes.data as MenuItem[])??[]);setLoading(false)};load();const t=window.setInterval(load,8000);return()=>{active=false;window.clearInterval(t)}},[]);
 const normalizedCategories=useMemo(()=>{const list=categories.map(c=>({...c,slug:slugify(c.slug||c.name)}));const required=[['cookies','Cookies'],['cheesecakes','Cheesecakes'],['croissants','Croissants'],['cake-jars','Cake Jars']];for(const [slug,name] of required)if(!list.some(c=>categoryMatches(c,slug)))list.push({id:`virtual-${slug}`,name,slug} as Category);return list},[categories]);
 const activeCategory=normalizedCategories.find(c=>categoryMatches(c,activeCat));
 const matchesCategory=(item:MenuItem,cat:Category)=>item.category_id===cat.id||categoryMatches(cat,itemCategorySlug(item));
 const matchesQuery=(item:MenuItem)=>{if(!query.trim())return true;const q=query.toLowerCase();return item.name.toLowerCase().includes(q)||item.description.toLowerCase().includes(q)||(item.tags??[]).some(t=>t.toLowerCase().includes(q))};
 const filtered=useMemo(()=>{let list=items;if(activeCat!=='all'&&activeCategory)list=list.filter(i=>matchesCategory(i,activeCategory));return list.filter(matchesQuery)},[items,activeCat,activeCategory,query]);
 const grouped=useMemo(()=>{if(activeCat!=='all'&&activeCategory)return [{category:activeCategory,items:filtered}];return normalizedCategories.map(c=>({category:c,items:items.filter(i=>matchesCategory(i,c)).filter(matchesQuery)}));},[items,normalizedCategories,activeCat,activeCategory,filtered,query]);
 const setCat=(slug:string)=>slug==='all'?setSearchParams({}):setSearchParams({cat:slugify(slug)});
 useEffect(()=>{if(loading||activeCat==='all')return;const id=window.requestAnimationFrame(()=>document.getElementById(`category-${slugify(activeCat)}`)?.scrollIntoView({behavior:'smooth',block:'start'}));return()=>window.cancelAnimationFrame(id)},[activeCat,loading,items.length,normalizedCategories.length]);
 return <div><section className="border-b border-bakery-primary/10 bg-gradient-to-b from-bakery-sky to-bakery-cream"><div className="container-bk py-12 text-center"><h1 className="font-display text-4xl font-bold text-bakery-ink sm:text-5xl">Our Menu</h1><p className="mx-auto mt-3 max-w-xl text-bakery-ink/60">Sixteen categories of freshly baked treats. Search, filter, and add your favourites to the cart.</p><div className="mx-auto mt-6 max-w-xl relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-bakery-ink/40"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search cakes, pastries, brownies..." className="w-full rounded-full border border-bakery-primary/15 bg-white py-3.5 pl-12 pr-12 text-sm text-bakery-ink placeholder:text-bakery-ink/40 shadow-soft focus:border-bakery-primary focus:outline-none focus:ring-2 focus:ring-bakery-primary/15"/>{query&&<button onClick={()=>setQuery('')} className="absolute right-4 top-1/2 -translate-y-1/2 text-bakery-ink/40 hover:text-bakery-ink/70"><X className="h-4 w-4"/></button>}</div></div></section><div className="sticky top-16 z-30 border-b border-bakery-primary/10 bg-white/90 backdrop-blur-md"><div className="container-bk flex items-center gap-2 py-3 overflow-x-auto no-scrollbar"><span className="hidden items-center gap-1.5 shrink-0 text-xs font-semibold uppercase tracking-wider text-bakery-ink/40 sm:flex"><SlidersHorizontal className="h-3.5 w-3.5"/>Filter:</span><CatPill active={activeCat==='all'} onClick={()=>setCat('all')} label="All"/>{normalizedCategories.map(c=><CatPill key={c.id} active={categoryMatches(c,activeCat)} onClick={()=>setCat(c.slug)} label={c.name}/>)}</div></div><section className="container-bk py-10">{loading?<div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{Array.from({length:8}).map((_,i)=><ProductCardSkeleton key={i}/>)}</div>:filtered.length===0&&activeCat!=='all'?<CategorySection category={activeCategory} items={[]}/>:filtered.length===0?<EmptyState icon={Search} title="No treats found" message="Try a different search or category — we have 100+ baked delights on the menu." actionLabel="Browse all" actionTo="/menu"/>:<div className="space-y-12">{grouped.filter(g=>activeCat!=='all'||g.items.length>0||String(g.category.id).startsWith('virtual-')).map(({category,items:catItems})=><CategorySection key={category.id} category={category} items={catItems}/>)}</div>}</section></div>;
}
function CategorySection({category,items}:{category?:Category;items:MenuItem[]}){if(!category)return null;return <div id={`category-${slugify(category.slug||category.name)}`} className="scroll-mt-32"><motion.h2 initial={{opacity:0,x:-10}} whileInView={{opacity:1,x:0}} viewport={{once:true}} className="mb-5 flex items-center gap-3 font-display text-2xl font-bold text-bakery-ink">{category.name}<span className="rounded-full bg-bakery-sky px-2.5 py-0.5 text-xs font-semibold text-bakery-primary">{items.length}</span></motion.h2>{items.length===0?<p className="rounded-2xl border border-dashed border-bakery-primary/15 bg-bakery-sky/30 p-8 text-center text-sm text-bakery-ink/50">No items are currently available in this category.</p>:<div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{items.map(item=><ProductCard key={item.id} item={item}/>)}</div>}</div>}
function CatPill({active,onClick,label}:{active:boolean;onClick:()=>void;label:string}){return <button onClick={onClick} className={`shrink-0 rounded-full px-4 py-1.5 text-sm font-medium transition-all ${active?'bg-bakery-primary text-white shadow-soft':'bg-bakery-sky/60 text-bakery-ink/70 hover:bg-bakery-sky hover:text-bakery-primary'}`}>{label}</button>}
