import { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Check, Leaf, Drumstick, Minus, Plus, ShoppingBag, Star, X } from 'lucide-react';
import type { MenuItem, PriceVariant } from '@/lib/types';
import { useCart } from '@/lib/cart';
import { useToast } from './Toast';
import { formatINR } from '@/lib/format';

export function ProductDetailSheet({ item, open, onClose }: { item: MenuItem; open: boolean; onClose: () => void }) {
 const {addItem}=useCart(); const {notify}=useToast();
 const variants=item.price_variants?.length?item.price_variants:[];
 const [selectedVariant,setSelectedVariant]=useState<PriceVariant|null>(variants[0]??null); const [quantity,setQuantity]=useState(1); const [added,setAdded]=useState(false);
 useEffect(()=>{setSelectedVariant(item.price_variants?.length?item.price_variants[0]:null);setQuantity(1);setAdded(false)},[item]);
 useEffect(()=>{if(!open)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};window.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;window.removeEventListener('keydown',key)}},[open,onClose]);
 const price=Number(selectedVariant?.price??item.price)||0;
 const handleAdd=()=>{if(!item.available||price<=0||added)return;addItem({id:item.id,name:item.name,image:item.image,price,variant_label:selectedVariant?.label??null,quantity});setAdded(true);notify(`${item.name} added to cart`,'success');onClose()};
 return <AnimatePresence initial={false}>
  {open&&<motion.div key="product-detail-root" className="fixed inset-0 z-[80] flex items-end justify-center sm:items-center sm:p-4" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.42,ease:[.22,1,.36,1]}}>
   <motion.button aria-label="Close product details" className="absolute inset-0 bg-bakery-ink/35 backdrop-blur-[2px]" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.38,ease:[.22,1,.36,1]}} onClick={onClose}/>
   <motion.section role="dialog" aria-modal="true" className="relative z-10 max-h-[92vh] w-full overflow-y-auto rounded-t-[28px] bg-white shadow-2xl sm:w-[min(920px,calc(100vw-32px))] sm:rounded-[28px]" initial={{y:'100%',opacity:0}} animate={{y:0,opacity:1}} exit={{y:'100%',opacity:0}} transition={{duration:.5,ease:[.22,1,.36,1]}}>
    <div className="sticky top-0 z-10 flex justify-end bg-white/90 px-4 pt-3 backdrop-blur"><button onClick={onClose} className="rounded-full bg-bakery-sky p-2 text-bakery-ink/70 hover:bg-bakery-primary hover:text-white"><X className="h-5 w-5"/></button></div>
    <div className="grid gap-6 px-5 pb-7 sm:grid-cols-[.95fr_1.05fr] sm:px-7 sm:pb-8"><div className="overflow-hidden rounded-2xl bg-bakery-cream-dark"><img src={item.image} alt={item.name} className="h-64 w-full object-cover sm:h-full sm:min-h-[360px]"/></div><div className="flex flex-col"><div className="flex flex-wrap gap-2"><span className="inline-flex items-center gap-1 rounded-full bg-accent-gold/15 px-2.5 py-1 text-xs font-bold text-accent-gold"><Star className="h-3.5 w-3.5 fill-current"/>Customer favourite</span><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-semibold ${item.veg?'bg-success/10 text-success':'bg-error/10 text-error'}`}>{item.veg?<Leaf className="h-3.5 w-3.5"/>:<Drumstick className="h-3.5 w-3.5"/>}{item.veg?'Veg':'Non-Veg'}</span></div><h2 className="mt-3 font-display text-2xl font-bold text-bakery-ink sm:text-3xl">{item.name}</h2><p className="mt-2 font-display text-2xl font-bold text-bakery-primary-dark">{formatINR(price)}</p><p className="mt-4 text-sm leading-7 text-bakery-ink/65">{item.description}</p>{item.tags?.length>0&&<div className="mt-4 flex flex-wrap gap-2">{item.tags.slice(0,6).map(tag=><span key={tag} className="rounded-full bg-bakery-sky px-3 py-1 text-xs font-medium text-bakery-primary">{tag}</span>)}</div>}{variants.length>0&&<div className="mt-5"><p className="mb-2 text-xs font-bold uppercase tracking-wide text-bakery-ink/45">Choose size</p><div className="flex flex-wrap gap-2">{variants.map(v=><button key={v.label} onClick={()=>setSelectedVariant(v)} className={`rounded-xl border px-3 py-2 text-sm font-semibold ${selectedVariant?.label===v.label?'border-bakery-primary bg-bakery-primary text-white':'border-bakery-primary/15 bg-white text-bakery-ink/70'}`}>{v.label} · {formatINR(v.price)}</button>)}</div></div>}<div className="mt-auto flex flex-wrap items-center gap-3 pt-6"><div className="flex items-center rounded-full border border-bakery-primary/15 bg-bakery-sky/40"><button onClick={()=>setQuantity(q=>Math.max(1,q-1))} className="p-3"><Minus className="h-4 w-4"/></button><span className="w-8 text-center text-sm font-bold">{quantity}</span><button onClick={()=>setQuantity(q=>q+1)} className="p-3"><Plus className="h-4 w-4"/></button></div><button onClick={handleAdd} disabled={!item.available||price<=0||added} className="inline-flex flex-1 items-center justify-center gap-2 rounded-full bg-bakery-primary px-5 py-3.5 text-sm font-bold text-white shadow-soft hover:bg-bakery-primary-dark disabled:opacity-60">{added?<Check className="h-5 w-5"/>:<ShoppingBag className="h-5 w-5"/>}{added?'Added to Cart':`Add to Cart · ${formatINR(price*quantity)}`}</button></div></div></div>
   </motion.section>
  </motion.div>}
 </AnimatePresence>;
}
