import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { TrendingUp, Package, Clock, ChefHat, Truck, CheckCircle2, Users, Star, ArrowRight, Calendar, IndianRupee, Cookie, Layers } from 'lucide-react';
import { adminApi, settingsApi, type CafeSettings } from '@/lib/api';
import { formatINR, formatDate } from '@/lib/format';
import type { Order } from '@/lib/types';
interface RevenuePoint { date:string; revenue:number; orders:number; }
interface Stats { total_orders:number; today_orders:number; revenue:number; pending_orders:number; preparing_orders:number; out_for_delivery:number; delivered_orders:number; cancelled_orders:number; customers:number; total_menu_items:number; category_count:number; pending_reviews:number; revenue_trend?:RevenuePoint[]; recent_orders:Order[]; }
const RANGE_OPTIONS=[{days:7,label:'7 Days'},{days:30,label:'30 Days'},{days:180,label:'6 Months'},{days:365,label:'1 Year'}] as const;
export default function AdminDashboard(){
 const [stats,setStats]=useState<Stats|null>(null);const [settings,setSettings]=useState<CafeSettings|null>(null);const [loading,setLoading]=useState(true);const [range,setRange]=useState(7);
 useEffect(()=>{let active=true;const load=async()=>{const [statsRes,settingsRes]=await Promise.all([adminApi.stats(range),settingsApi.get()]);if(!active)return;if(statsRes.success&&statsRes.data)setStats(statsRes.data as Stats);if(settingsRes.success&&settingsRes.data)setSettings(settingsRes.data);setLoading(false)};load();const t=window.setInterval(load,4000);return()=>{active=false;window.clearInterval(t)}},[range]);
 const cards=[{label:'Total Orders',value:stats?.total_orders??0,icon:Package,color:'text-bakery-primary',bg:'bg-bakery-sky'},{label:"Today's Orders",value:stats?.today_orders??0,icon:Calendar,color:'text-bakery-primary-dark',bg:'bg-bakery-sky'},{label:'Revenue',value:formatINR(stats?.revenue??0),icon:IndianRupee,color:'text-success',bg:'bg-success/10'},{label:'Pending',value:stats?.pending_orders??0,icon:Clock,color:'text-warning',bg:'bg-warning/10'},{label:'Preparing',value:stats?.preparing_orders??0,icon:ChefHat,color:'text-bakery-primary',bg:'bg-bakery-sky'},{label:'Out for Delivery',value:stats?.out_for_delivery??0,icon:Truck,color:'text-bakery-primary-dark',bg:'bg-bakery-sky'},{label:'Delivered',value:stats?.delivered_orders??0,icon:CheckCircle2,color:'text-success',bg:'bg-success/10'},{label:'Cancelled',value:stats?.cancelled_orders??0,icon:Package,color:'text-error',bg:'bg-error/10'},{label:'Customers',value:stats?.customers??0,icon:Users,color:'text-bakery-primary',bg:'bg-bakery-sky'},{label:'Menu Items',value:stats?.total_menu_items??0,icon:Cookie,color:'text-bakery-primary-dark',bg:'bg-bakery-sky'},{label:'Categories',value:stats?.category_count??0,icon:Layers,color:'text-bakery-primary',bg:'bg-bakery-sky'},{label:'Pending Reviews',value:stats?.pending_reviews??0,icon:Star,color:'text-accent-gold',bg:'bg-accent-gold/15'}];
 const trend=useMemo(()=>Array.isArray(stats?.revenue_trend)?stats!.revenue_trend.map(p=>({date:p.date,revenue:Number(p.revenue)||0,orders:Number(p.orders)||0})):[],[stats]);const maxRevenue=Math.max(...trend.map(p=>p.revenue),1);const totalTrend=trend.reduce((sum,p)=>sum+p.revenue,0);const latest=trend.at(-1)?.revenue??0;const previous=trend.at(-2)?.revenue??0;const delta=previous>0?((latest-previous)/previous)*100:null;
 const points=trend.map((p,i)=>{const x=8+(i*(84/Math.max(trend.length-1,1)));const y=72-(p.revenue/maxRevenue)*54;return {...p,x,y}});const line=points.map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' ');const area=points.length>1?`${line} L ${points.at(-1)!.x} 78 L ${points[0].x} 78 Z`:'';const labelEvery=trend.length<=10?1:Math.ceil(trend.length/7);const dateLabel=(date:string)=>{const d=new Date(`${date}T12:00:00`);return range<=30?d.toLocaleDateString('en-IN',{day:'numeric',month:'short'}):d.toLocaleDateString('en-IN',{month:'short',year:'2-digit'})};
 if(loading)return <div className="flex min-h-[40vh] items-center justify-center"><div className="h-8 w-8 animate-spin rounded-full border-2 border-bakery-primary/20 border-t-bakery-primary"/></div>;
 return <div className="w-full min-w-0 max-w-full overflow-hidden"><h1 className="mb-6 font-display text-2xl font-bold text-bakery-ink">Dashboard</h1>
  <div className="grid min-w-0 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{cards.map((c,i)=><motion.div key={c.label} initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:i*.03}} className="card min-w-0 p-5"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${c.bg} ${c.color}`}><c.icon className="h-5 w-5"/></div><p className="mt-3 truncate font-display text-2xl font-bold text-bakery-ink">{c.value}</p><p className="truncate text-sm text-bakery-ink/55">{c.label}</p></motion.div>)}</div>
  <motion.section initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="card mt-8 w-full min-w-0 max-w-full overflow-hidden p-4 sm:p-6"><div className="flex min-w-0 flex-col gap-4">
   <div className="flex min-w-0 flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex min-w-0 items-center gap-2"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-bakery-sky text-bakery-primary"><TrendingUp className="h-4 w-4"/></div><h2 className="truncate font-display text-lg font-semibold text-bakery-ink">Revenue Trend</h2></div><p className="mt-1 text-xs text-bakery-ink/50">Overall revenue · {RANGE_OPTIONS.find(x=>x.days===range)?.label} · <span className="inline-flex items-center gap-1 font-semibold"><span className={`h-2 w-2 rounded-full ${settings?.restaurantOpen===false?'bg-error':'bg-success animate-pulse'}`}/>{settings?.restaurantOpen===false?'Cafe Closed':'Live'}</span></p></div>
    <div className="flex min-w-0 flex-col gap-3 sm:flex-row sm:items-center lg:justify-end"><div className="flex w-fit max-w-full flex-wrap gap-1.5 rounded-xl bg-bakery-sky/45 p-1">{RANGE_OPTIONS.map(opt=><button key={opt.days} onClick={()=>setRange(opt.days)} className={`rounded-lg px-2.5 py-1.5 text-xs font-semibold transition-all sm:px-3 ${range===opt.days?'bg-bakery-primary text-white shadow-sm':'text-bakery-ink/55 hover:bg-white'}`}>{opt.label}</button>)}</div><div className="min-w-0 text-left sm:text-right"><p className="font-display text-xl font-bold text-bakery-primary-dark">{formatINR(totalTrend)}</p><p className={`text-xs font-semibold ${delta===null?'text-bakery-ink/45':delta>=0?'text-success':'text-error'}`}>{delta===null?'Waiting for comparison':`${delta>=0?'+':''}${delta.toFixed(1)}% vs previous data point`}</p></div></div></div>
   <div className="w-full min-w-0 overflow-hidden rounded-2xl bg-bakery-sky/35 p-2 sm:p-4">{points.length<2?<div className="flex h-52 items-center justify-center text-sm text-bakery-ink/45">Revenue data will appear here as orders come in.</div>:<><div className="relative h-52 w-full min-w-0 sm:h-60"><svg viewBox="0 0 100 84" preserveAspectRatio="xMidYMid meet" className="block h-full w-full overflow-visible" role="img" aria-label={`${RANGE_OPTIONS.find(x=>x.days===range)?.label} revenue trend`}><defs><linearGradient id="bakestRevenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="currentColor" stopOpacity="0.20"/><stop offset="100%" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs><path d="M 8 78 L 92 78" stroke="currentColor" strokeOpacity="0.12" vectorEffect="non-scaling-stroke"/><path d="M 8 51 L 92 51" stroke="currentColor" strokeOpacity="0.08" strokeDasharray="3 3" vectorEffect="non-scaling-stroke"/><path d="M 8 24 L 92 24" stroke="currentColor" strokeOpacity="0.08" strokeDasharray="3 3" vectorEffect="non-scaling-stroke"/><path d={area} fill="url(#bakestRevenueFill)" className="text-bakery-primary"/><path d={line} fill="none" stroke="currentColor" strokeWidth="2.2" vectorEffect="non-scaling-stroke" className="text-bakery-primary" strokeLinecap="round" strokeLinejoin="round"/>{points.map(p=><g key={p.date} className="cursor-pointer"><circle cx={p.x} cy={p.y} r="2.1" className="fill-white stroke-bakery-primary" strokeWidth="1.4" vectorEffect="non-scaling-stroke"/><title>{dateLabel(p.date)} · Revenue: {formatINR(p.revenue)} · Orders: {p.orders}</title></g>)}</svg></div><div className="mt-1 grid grid-cols-7 gap-1 text-center text-[9px] text-bakery-ink/45 sm:text-[10px]">{points.map((p,i)=><span key={`${p.date}-label`} className={i%labelEvery===0||i===points.length-1?'':'invisible'}>{dateLabel(p.date)}</span>)}</div></>}</div>
  </div></motion.section>
  <div className="mt-8 grid min-w-0 gap-4 sm:grid-cols-2 lg:grid-cols-3"><Link to="/admin/orders" className="card group flex min-w-0 items-center justify-between p-5 transition-all hover:shadow-card"><div className="flex min-w-0 items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-bakery-sky text-bakery-primary"><Package className="h-5 w-5"/></div><div className="min-w-0"><p className="truncate font-display text-sm font-semibold text-bakery-ink">Manage Orders</p><p className="truncate text-xs text-bakery-ink/50">{stats?.pending_orders??0} pending to confirm</p></div></div><ArrowRight className="h-5 w-5 shrink-0 text-bakery-ink/30"/></Link><Link to="/admin/reviews" className="card group flex min-w-0 items-center justify-between p-5 transition-all hover:shadow-card"><div className="flex min-w-0 items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-accent-gold/15 text-accent-gold"><Star className="h-5 w-5"/></div><div className="min-w-0"><p className="truncate font-display text-sm font-semibold text-bakery-ink">Moderate Reviews</p><p className="truncate text-xs text-bakery-ink/50">{stats?.pending_reviews??0} awaiting approval</p></div></div><ArrowRight className="h-5 w-5 shrink-0 text-bakery-ink/30"/></Link><Link to="/admin/menu" className="card group flex min-w-0 items-center justify-between p-5 transition-all hover:shadow-card"><div className="flex min-w-0 items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-bakery-sky text-bakery-primary"><TrendingUp className="h-5 w-5"/></div><div className="min-w-0"><p className="truncate font-display text-sm font-semibold text-bakery-ink">Manage Menu</p><p className="truncate text-xs text-bakery-ink/50">Add, edit & update products</p></div></div><ArrowRight className="h-5 w-5 shrink-0 text-bakery-ink/30"/></Link></div>
  <div className="mt-8 min-w-0"><h2 className="mb-4 font-display text-lg font-semibold text-bakery-ink">Recent Orders</h2>{(stats?.recent_orders??[]).length===0?<div className="card p-8 text-center"><Package className="mx-auto h-10 w-10 text-bakery-primary/30"/><p className="mt-3 text-sm text-bakery-ink/50">No orders yet.</p></div>:<div className="card min-w-0 divide-y divide-bakery-primary/10 overflow-hidden">{(stats?.recent_orders??[]).map(o=><Link key={o.id} to={`/orders/${o.id}`} className="flex min-w-0 items-center gap-3 p-4 transition-colors hover:bg-bakery-sky/30 sm:gap-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-bakery-sky text-bakery-primary"><Package className="h-5 w-5"/></div><div className="min-w-0 flex-1"><p className="truncate font-display text-sm font-semibold text-bakery-ink">{o.order_number}</p><p className="truncate text-xs text-bakery-ink/50">{o.customer_name} · {formatDate(o.created_at)}</p></div><p className="shrink-0 font-display text-sm font-bold text-bakery-primary-dark">{formatINR(o.total)}</p><span className={`badge hidden shrink-0 px-2.5 py-1 text-xs sm:inline-flex ${o.status==='delivered'?'bg-success/10 text-success':o.status==='cancelled'?'bg-error/10 text-error':'bg-bakery-sky text-bakery-primary'}`}>{o.status.replace(/_/g,' ')}</span></Link>)}</div>}</div>
 </div>;
}
