import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Star, Check, X, Trash2, MessageSquare } from 'lucide-react';
import { reviewsApi } from '@/lib/api';
import type { Review, ReviewStatus } from '@/lib/types';
import { formatDate } from '@/lib/format';
import { useToast } from '@/components/Toast';

export default function AdminReviews(){
 const [reviews,setReviews]=useState<Review[]>([]);const [loading,setLoading]=useState(true);const [tab,setTab]=useState<ReviewStatus>('pending');const {notify}=useToast();
 const load=async()=>{const res=await reviewsApi.all();if(res.success)setReviews((res.data as Review[])??[]);setLoading(false)};
 useEffect(()=>{load();const t=window.setInterval(load,5000);return()=>window.clearInterval(t)},[]);
 const moderate=async(id:string,action:'approve'|'reject'|'delete')=>{const res=await reviewsApi.moderate(id,action);if(!res.success)notify(res.message||'Action failed','error');else{setReviews(prev=>action==='delete'?prev.filter(r=>r.id!==id):prev.map(r=>r.id===id?{...r,status:action==='approve'?'approved':'rejected'}:r));notify(action==='delete'?'Review deleted':`Review ${action}d`,'success')}};
 const tabs: {value:ReviewStatus;label:string}[]=[{value:'pending',label:'Pending'},{value:'approved',label:'Approved'},{value:'rejected',label:'Rejected'}];
 const filtered=reviews.filter(r=>r.status===tab);
 return <div><h1 className="mb-6 font-display text-2xl font-bold text-bakery-ink">Reviews</h1><div className="mb-6 flex gap-2">{tabs.map(t=><button key={t.value} onClick={()=>setTab(t.value)} className={`rounded-full px-4 py-1.5 text-sm font-medium transition-all ${tab===t.value?'bg-bakery-primary text-white':'bg-white text-bakery-ink/60 hover:bg-bakery-sky'}`}>{t.label}<span className="ml-1.5 text-xs opacity-70">({reviews.filter(r=>r.status===t.value).length})</span></button>)}</div>{loading?<div className="flex justify-center py-20"><div className="h-8 w-8 animate-spin rounded-full border-2 border-bakery-primary/20 border-t-bakery-primary"/></div>:filtered.length===0?<div className="card p-12 text-center"><MessageSquare className="mx-auto h-10 w-10 text-bakery-primary/30"/><p className="mt-3 text-sm text-bakery-ink/50">No {tab} reviews.</p></div>:<div className="space-y-4">{filtered.map((r,i)=><motion.div key={r.id} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:i*.05}} className="card p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex-1 min-w-0"><div className="flex items-center gap-2"><div className="flex items-center gap-0.5 text-accent-gold">{Array.from({length:r.rating}).map((_,s)=><Star key={s} className="h-4 w-4 fill-accent-gold"/>)}</div><span className="text-sm font-semibold text-bakery-ink">{r.user_name||'Anonymous'}</span><span className="text-xs text-bakery-ink/40">{formatDate(r.created_at)}</span></div><p className="mt-2 text-sm leading-relaxed text-bakery-ink/70">"{r.comment}"</p></div><div className="flex gap-1.5">{r.status==='pending'&&<><button onClick={()=>moderate(r.id,'approve')} className="rounded-lg p-2 text-success hover:bg-success/10" title="Approve"><Check className="h-4 w-4"/></button><button onClick={()=>moderate(r.id,'reject')} className="rounded-lg p-2 text-warning hover:bg-warning/10" title="Reject"><X className="h-4 w-4"/></button></>}{r.status==='rejected'&&<button onClick={()=>moderate(r.id,'approve')} className="rounded-lg p-2 text-success hover:bg-success/10" title="Approve"><Check className="h-4 w-4"/></button>}{r.status==='approved'&&<button onClick={()=>moderate(r.id,'reject')} className="rounded-lg p-2 text-warning hover:bg-warning/10" title="Unpublish"><X className="h-4 w-4"/></button>}<button onClick={()=>moderate(r.id,'delete')} className="rounded-lg p-2 text-error hover:bg-error/10" title="Delete"><Trash2 className="h-4 w-4"/></button></div></div></motion.div>)}</div>}</div>;
}
