import { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Package, ChevronDown, Phone, MapPin, CreditCard, BellRing } from 'lucide-react';
import { ordersApi } from '@/lib/api';
import type { Order, OrderStatus } from '@/lib/types';
import { ORDER_STATUSES } from '@/lib/types';
import { formatINR, formatDate } from '@/lib/format';
import { useToast } from '@/components/Toast';

const statusOptions: OrderStatus[]=['placed','confirmed','preparing','ready','out_for_delivery','delivered','cancelled'];
export default function AdminOrders(){
 const [orders,setOrders]=useState<Order[]>([]);const [loading,setLoading]=useState(true);const [filter,setFilter]=useState<OrderStatus|'all'>('all');const [expanded,setExpanded]=useState<string|null>(null);const {notify}=useToast();
 const loadOrders=async()=>{const res=await ordersApi.list();if(res.success)setOrders((res.data as Order[])??[]);setLoading(false)};
 useEffect(()=>{loadOrders();const t=window.setInterval(loadOrders,4000);return()=>window.clearInterval(t)},[]);
 const updateStatus=async(orderId:string,status:OrderStatus)=>{const res=await ordersApi.updateStatus(orderId,status);if(!res.success)notify(res.message||'Could not update status','error');else{setOrders(prev=>prev.map(o=>o.id===orderId?{...o,status}:o));notify(`Order updated to ${status.replace(/_/g,' ')}`,'success')}};
 const filtered=filter==='all'?orders:orders.filter(o=>o.status===filter);const tabs=[{value:'all' as const,label:'All'},...ORDER_STATUSES.map(s=>({value:s.value,label:s.label})),{value:'cancelled' as const,label:'Cancelled'}];
 return <div className="mx-auto w-full min-w-0 max-w-full">
  <div className="mb-5 flex min-w-0 flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h1 className="font-display text-2xl font-bold text-bakery-ink">Orders</h1><span className="inline-flex w-fit max-w-full items-center gap-2 rounded-full bg-bakery-sky px-3 py-1.5 text-xs font-semibold text-bakery-primary"><BellRing className="h-3.5 w-3.5 shrink-0"/>Live updates</span></div>
  <div className="mb-5 flex w-full min-w-0 flex-wrap items-center justify-center gap-2 pb-1 sm:justify-start">{tabs.map(t=><button key={t.value} onClick={()=>setFilter(t.value)} className={`shrink-0 rounded-full px-3 py-1.5 text-xs font-medium transition-all sm:px-4 sm:text-sm ${filter===t.value?'bg-bakery-primary text-white':'bg-white text-bakery-ink/60 hover:bg-bakery-sky'}`}>{t.label}</button>)}</div>
  {loading?<div className="flex justify-center py-20"><div className="h-8 w-8 animate-spin rounded-full border-2 border-bakery-primary/20 border-t-bakery-primary"/></div>:filtered.length===0?<div className="card w-full p-8 text-center sm:p-12"><Package className="mx-auto h-10 w-10 text-bakery-primary/30"/><p className="mt-3 text-sm text-bakery-ink/50">No orders in this category.</p></div>:<div className="mx-auto w-full min-w-0 space-y-3">
   {filtered.map(o=><motion.div key={o.id} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="card mx-auto w-full min-w-0 max-w-full overflow-hidden">
    <button onClick={()=>setExpanded(expanded===o.id?null:o.id)} className="grid w-full min-w-0 grid-cols-[auto_minmax(0,1fr)_auto_auto] items-center gap-2 p-3 text-left sm:flex sm:gap-4 sm:p-4">
      <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-bakery-sky text-bakery-primary sm:h-10 sm:w-10"><Package className="h-4 w-4 sm:h-5 sm:w-5"/></div>
      <div className="min-w-0 overflow-hidden sm:flex-1"><p className="truncate font-display text-sm font-semibold text-bakery-ink">{o.order_number}</p><p className="truncate text-xs text-bakery-ink/50">{o.customer_name} · {formatDate(o.created_at)}</p></div>
      <div className="col-start-2 row-start-2 min-w-0 text-left sm:order-none sm:col-auto sm:row-auto sm:shrink-0 sm:text-right"><p className="font-display text-sm font-bold text-bakery-primary-dark">{formatINR(o.total)}</p><p className="truncate text-[10px] text-bakery-ink/50 sm:text-xs">{o.items.length} item(s) · {o.payment_method.toUpperCase()}</p></div>
      <span className={`max-w-full justify-self-end truncate rounded-full px-2 py-1 text-[10px] font-semibold uppercase sm:px-2.5 sm:text-xs ${o.status==='delivered'?'bg-success/10 text-success':o.status==='cancelled'?'bg-error/10 text-error':'bg-bakery-sky text-bakery-primary'}`}>{o.status.replace(/_/g,' ')}</span>
      <ChevronDown className={`h-4 w-4 shrink-0 text-bakery-ink/30 transition-transform sm:order-last ${expanded===o.id?'rotate-180':''}`}/>
    </button>
    <AnimatePresence>{expanded===o.id&&<motion.div initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden border-t border-bakery-primary/10"><div className="grid w-full min-w-0 gap-5 p-3 sm:grid-cols-2 sm:p-4">
      <div className="min-w-0"><h4 className="mb-2 text-xs font-semibold uppercase tracking-wider text-bakery-ink/40">Items</h4><div className="space-y-2">{o.items.map((item,i)=><div key={`${item.id}-${i}`} className="flex min-w-0 items-center gap-2 text-sm"><img src={item.image} alt={item.name} className="h-8 w-8 shrink-0 rounded-lg object-cover"/><span className="min-w-0 flex-1 truncate text-bakery-ink/70">{item.name} {item.variant_label?`(${item.variant_label})`:''} ×{item.quantity}</span><span className="shrink-0 font-medium text-bakery-ink">{formatINR(item.price*item.quantity)}</span></div>)}</div><div className="mt-3 space-y-1 border-t border-bakery-primary/10 pt-2 text-sm"><div className="flex justify-between gap-3 text-bakery-ink/60"><span>Subtotal</span><span className="shrink-0">{formatINR(o.subtotal)}</span></div><div className="flex justify-between gap-3 text-bakery-ink/60"><span>Delivery</span><span className="shrink-0">{formatINR(o.delivery_charge)}</span></div><div className="flex justify-between gap-3 font-semibold"><span>Total</span><span className="shrink-0 text-bakery-primary-dark">{formatINR(o.total)}</span></div></div></div>
      <div className="min-w-0"><h4 className="mb-2 text-xs font-semibold uppercase tracking-wider text-bakery-ink/40">Customer</h4><div className="space-y-1.5 text-sm text-bakery-ink/70"><p className="break-words">{o.customer_name}</p><p className="flex min-w-0 items-center gap-1.5 break-all"><Phone className="h-3.5 w-3.5 shrink-0 text-bakery-primary"/>{o.customer_phone}</p><p className="flex min-w-0 items-start gap-1.5 break-words"><MapPin className="mt-0.5 h-3.5 w-3.5 shrink-0 text-bakery-primary"/><span>{o.address}, {o.city} - {o.pincode}</span></p><p className="flex items-center gap-1.5"><CreditCard className="h-3.5 w-3.5 shrink-0 text-bakery-primary"/>{o.payment_method==='cod'?'Cash on Delivery':'Online'}</p>{o.instructions&&<p className="break-words text-xs italic text-bakery-ink/50">Note: {o.instructions}</p>}</div><h4 className="mb-2 mt-4 text-xs font-semibold uppercase tracking-wider text-bakery-ink/40">Update Status</h4><div className="grid w-full grid-cols-2 gap-1.5 min-[380px]:grid-cols-3 sm:flex sm:flex-wrap">{statusOptions.map(s=><button key={s} onClick={()=>updateStatus(o.id,s)} className={`min-w-0 rounded-full px-2 py-1.5 text-[10px] font-medium capitalize transition-all sm:px-3 sm:py-1 sm:text-xs ${o.status===s?'bg-bakery-primary text-white':'bg-bakery-sky/60 text-bakery-ink/60 hover:bg-bakery-sky'}`}>{s.replace(/_/g,' ')}</button>)}</div></div>
    </div></motion.div>}</AnimatePresence>
   </motion.div>)}
  </div>}
 </div>;
}
