import { useEffect, useState } from 'react';
import { Save, Store, ExternalLink, Clock3, Truck, Instagram, Facebook, Twitter } from 'lucide-react';
import { defaultCafeSettings, settingsApi, type CafeSettings } from '@/lib/api';
import { useCafeSettings } from '@/lib/cafe-settings';
import { useToast } from '@/components/Toast';

const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
export default function AdminSettings(){
 const {settings,refresh}=useCafeSettings(); const {notify}=useToast(); const [form,setForm]=useState<CafeSettings>(defaultCafeSettings); const [saving,setSaving]=useState(false);
 useEffect(()=>setForm({...settings,openingHours:{...settings.openingHours}}),[settings]);
 const set=(key:keyof CafeSettings,value:unknown)=>setForm(p=>({...p,[key]:value}));
 const save=async()=>{setSaving(true);const res=await settingsApi.update(form);setSaving(false);if(res.success){await refresh();notify('Cafe settings saved — changes are live','success')}else notify(res.message||'Could not save settings','error')};
 return <div className="min-w-0 w-full"><div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="font-display text-2xl font-bold text-bakery-ink">Cafe Settings</h1><p className="mt-1 text-sm text-bakery-ink/50">Control your store information and website content live.</p></div><a href="/" target="_blank" rel="noreferrer" className="btn-secondary w-fit"><ExternalLink className="h-4 w-4"/> View Store</a></div>
 <div className="space-y-6">
  <section className="card p-5 sm:p-6"><div className="mb-5 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-bakery-sky text-bakery-primary"><Store className="h-5 w-5"/></div><div><h2 className="font-display font-semibold">Restaurant Information</h2><p className="text-xs text-bakery-ink/50">These details update across the customer website automatically.</p></div></div><div className="grid gap-4 sm:grid-cols-2">
   {([['restaurantName','Restaurant Name'],['tagline','Tagline'],['phone','Phone'],['email','Email'],['address','Address'],['logoUrl','Logo URL'],['heroImageUrl','Hero Image URL'],['storyImageUrl','Story Image URL']] as const).map(([key,label])=><label key={key} className="block"><span className="mb-1.5 block text-xs font-semibold text-bakery-ink/60">{label}</span><input value={String(form[key]??'')} onChange={e=>set(key,e.target.value)} className="input-bk w-full" placeholder={label}/></label>)}
 </div></section>
 <section className="card p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-display font-semibold">Restaurant Open</h2><p className="text-xs text-bakery-ink/50">Turn ordering availability on or off instantly.</p></div><button type="button" onClick={()=>set('restaurantOpen',!form.restaurantOpen)} className={`relative h-7 w-12 rounded-full transition-colors ${form.restaurantOpen?'bg-success':'bg-bakery-ink/20'}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition-transform ${form.restaurantOpen?'left-6':'left-1'}`}/></button></div></section>
 <section className="card p-5 sm:p-6"><div className="mb-5 flex items-center gap-3"><Clock3 className="h-5 w-5 text-bakery-primary"/><div><h2 className="font-display font-semibold">Opening Hours</h2><p className="text-xs text-bakery-ink/50">Set each day independently.</p></div></div><div className="space-y-3">{days.map(day=><div key={day} className="grid grid-cols-[90px_minmax(0,1fr)] items-center gap-3"><span className="text-sm font-medium text-bakery-ink/70">{day}</span><input value={form.openingHours[day]||''} onChange={e=>setForm(p=>({...p,openingHours:{...p.openingHours,[day]:e.target.value}}))} className="input-bk w-full" placeholder="11:00 AM - 11:00 PM"/></div>)}</div></section>
 <section className="card p-5 sm:p-6"><div className="mb-5 flex items-center gap-3"><Truck className="h-5 w-5 text-bakery-primary"/><h2 className="font-display font-semibold">Delivery & Tax</h2></div><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-1.5 block text-xs font-semibold text-bakery-ink/60">Delivery Charge (₹)</span><input type="number" min="0" value={form.deliveryCharge} onChange={e=>set('deliveryCharge',Number(e.target.value)||0)} className="input-bk w-full"/></label><label><span className="mb-1.5 block text-xs font-semibold text-bakery-ink/60">Tax Rate (%)</span><input type="number" min="0" max="100" value={form.taxRate} onChange={e=>set('taxRate',Number(e.target.value)||0)} className="input-bk w-full"/></label></div></section>
 <section className="card p-5 sm:p-6"><h2 className="mb-5 font-display font-semibold">Social Links</h2><div className="grid gap-4 sm:grid-cols-3"><label><span className="mb-1.5 flex items-center gap-1 text-xs font-semibold text-bakery-ink/60"><Instagram className="h-3.5 w-3.5"/>Instagram</span><input value={form.instagram} onChange={e=>set('instagram',e.target.value)} className="input-bk w-full"/></label><label><span className="mb-1.5 flex items-center gap-1 text-xs font-semibold text-bakery-ink/60"><Facebook className="h-3.5 w-3.5"/>Facebook</span><input value={form.facebook} onChange={e=>set('facebook',e.target.value)} className="input-bk w-full"/></label><label><span className="mb-1.5 flex items-center gap-1 text-xs font-semibold text-bakery-ink/60"><Twitter className="h-3.5 w-3.5"/>Twitter</span><input value={form.twitter} onChange={e=>set('twitter',e.target.value)} className="input-bk w-full"/></label></div></section>
 <div className="sticky bottom-3 z-10 flex justify-end"><button onClick={save} disabled={saving} className="btn-primary shadow-card"><Save className="h-4 w-4"/>{saving?'Saving...':'Save Settings'}</button></div>
 </div></div>
}
