import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { TrendingUp, Package, Clock, ChefHat, Truck, CheckCircle2, Users, Star, ArrowRight, Calendar, IndianRupee, Cookie, Layers } from 'lucide-react';
import { adminApi, settingsApi, type CafeSettings } from '@/lib/api';
import { formatINR, formatDate } from '@/lib/format';
import type { Order } from '@/lib/types';
interface RevenuePoint { date:string; revenue:number; orders:number; }
interface Stats { total_orders:number; today_orders:number; revenue:number; pending_orders:number; preparing_orders:number; out_for_delivery:number; delivered_orders:number; cancelled_orders:number; customers:number; total_menu_items:number; category_count:number; pending_reviews:number; revenue_trend?:RevenuePoint[]; recent_orders:Order[]; }
const RANGE_OPTIONS=[{days:7,label:'7 Days'},{days:30,label:'30 Days'},{days:180,label:'6 Months'},{days:365,label:'1 Year'}] as const;
const DAY_MS=86400000;
function parseDate(value:string){const d=new Date(`${String(value).slice(0,10)}T12:00:00`);return Number.isNaN(d.getTime())?null:d;}
export default function AdminDashboard(){
 const [stats,setStats]=useState<Stats|null>(null);const [settings,setSettings]=useState<CafeSettings|null>(null);const [loading,setLoading]=useState(true);const [range,setRange]=useState(7);
 useEffect(()=>{let active=true;const load=async()=>{const [statsRes,settingsRes]=await Promise.all([adminApi.stats(range),settingsApi.get()]);if(!active)return;if(statsRes.success&&statsRes.data)setStats(statsRes.data as Stats);if(settingsRes.success&&settingsRes.data)setSettings(settingsRes.data);setLoading(false)};load();const t=window.setInterval(load,4000);return()=>{active=false;window.clearInterval(t)}},[range]);
 const cards=[{label:'Total Orders',value:stats?.total_orders??0,icon:Package,color:'text-bakery-primary',bg:'bg-bakery-sky'},{label:"Today's Orders",value:stats?.today_orders??0,icon:Calendar,color:'text-bakery-primary-dark',bg:'bg-bakery-sky'},{label:'Revenue',value:formatINR(stats?.revenue??0),icon:IndianRupee,color:'text-success',bg:'bg-success/10'},{label:'Pending',value:stats?.pending_orders??0,icon:Clock,color:'text-warning',bg:'bg-warning/10'},{label:'Preparing',value:stats?.preparing_orders??0,icon:ChefHat,color:'text-bakery-primary',bg:'bg-bakery-sky'},{label:'Out for Delivery',value:stats?.out_for_delivery??0,icon:Truck,color:'text-bakery-primary-dark',bg:'bg-bakery-sky'},{label:'Delivered',value:stats?.delivered_orders??0,icon:CheckCircle2,color:'text-success',bg:'bg-success/10'},{label:'Cancelled',value:stats?.cancelled_orders??0,icon:Package,color:'text-error',bg:'bg-error/10'},{label:'Customers',value:stats?.customers??0,icon:Users,color:'text-bakery-primary',bg:'bg-bakery-sky'},{label:'Menu Items',value:stats?.total_menu_items??0,icon:Cookie,color:'text-bakery-primary-dark',bg:'bg-bakery-sky'},{label:'Categories',value:stats?.category_count??0,icon:Layers,color:'text-bakery-primary',bg:'bg-bakery-sky'},{label:'Pending Reviews',value:stats?.pending_reviews??0,icon:Star,color:'text-accent-gold',bg:'bg-accent-gold/15'}];
 const trend=useMemo(()=>Array.isArray(stats?.revenue_trend)?stats!.revenue_trend.map(p=>({date:String(p.date).slice(0,10),revenue:Number(p.revenue)||0,orders:Number(p.orders)||0})).filter(p=>parseDate(p.date)):[],[stats]);
 const maxRevenue=Math.max(...trend.map(p=>p.revenue),1);const totalTrend=trend.reduce((sum,p)=>sum+p.revenue,0);const latest=trend.at(-1)?.revenue??0;const previous=trend.at(-2)?.revenue??0;const delta=previous>0?((latest-previous)/previous)*100:null;
 const bars=useMemo(()=>{const valid=trend.map(p=>({...p,day:parseDate(p.date)!}));if(!valid.length)return[];const latestDay=valid.reduce((a,b)=>a.day>b.day?a:b).day;const startDay=new Date(latestDay.getTime()-(range-1)*DAY_MS);const span=Math.max(range-1,1);const slot=90/span;return valid.map(p=>{const diff=Math.round((p.day.getTime()-startDay.getTime())/DAY_MS);const x=5+Math.min(span,Math.max(0,diff))*(90/span);const height=Math.max((p.revenue/maxRevenue)*66,1.5);const width=Math.max(0.9,Math.min(7,slot*0.58));return {...p,x,height,width}})},[trend,range,maxRevenue]);
 const labelDates=useMemo(()=>{if(!bars.length)return[];const latestDay=bars.reduce((a,b)=>a.day>b.day?a:b).day;const startDay=new Date(latestDay.getTime()-(range-1)*DAY_MS);const count=range<=7?7:6;return Array.from({length:count},(_,i)=>new Date(startDay.getTime()+((range-1)*i/Math.max(count-1,1))*DAY_MS))},[bars,range]);
 const dateLabel=(date:string|Date)=>{const d=date instanceof Date?date:parseDate(date);if(!d)return'';return range<=30?d.toLocaleDateString('en-IN',{day:'numeric',month:'short'}):d.toLocaleDateString('en-IN',{month:'short',year:'2-digit'});};
 if(loading)return <div className="flex min-h-[40vh] items-center justify-center"><div className="h-8 w-8 animate-spin rounded-full border-2 border-bakery-primary/20 border-t-bakery-primary"/></div>;
 return <div className="w-full min-w-0 max-w-full overflow-hidden"><h1 className="mb-6 font-display text-2xl font-bold text-bakery-ink">Dashboard</h1>
  <div className="grid min-w-0 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{cards.map((c,i)=><motion.div key={c.label} initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:i*.03}} className="card min-w-0 p-5"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${c.bg} ${c.color}`}><c.icon className="h-5 w-5"/></div><p className="mt-3 truncate font-display text-2xl font-bold text-bakery-ink">{c.value}</p><p className="truncate text-sm text-bakery-ink/55">{c.label}</p></motion.div>)}</div>
  <motion.section initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="card mt-8 w-full min-w-0 max-w-full overflow-hidden p-4 sm:p-6"><div className="flex min-w-0 flex-col gap-4">
   <div className="flex min-w-0 flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex min-w-0 items-center gap-2"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-bakery-sky text-bakery-primary"><TrendingUp className="h-4 w-4"/></div><h2 className="truncate font-display text-lg font-semibold text-bakery-ink">Revenue Trend</h2></div><p className="mt-1 text-xs text-bakery-ink/50">Overall revenue · {RANGE_OPTIONS.find(x=>x.days===range)?.label} · <span className="inline-flex items-center gap-1 font-semibold">{settings?.restaurantOpen===false?<span className="h-2 w-2 rounded-full bg-error"/>:<span className="relative inline-flex h-2 w-2"><span className="absolute inline-flex h-full w-full rounded-full bg-success/50 animate-ping"/><span className="relative inline-flex h-2 w-2 rounded-full bg-success"/></span>}{settings?.restaurantOpen===false?'Cafe Closed':'Live'}</span></p></div>
    <div className="flex min-w-0 flex-col gap-3 sm:flex-row sm:items-center lg:justify-end"><div className="flex w-fit max-w-full flex-wrap gap-1.5 rounded-xl bg-bakery-sky/45 p-1">{RANGE_OPTIONS.map(opt=><button key={opt.days} onClick={()=>setRange(opt.days)} className={`rounded-lg px-2.5 py-1.5 text-xs font-semibold transition-all sm:px-3 ${range===opt.days?'bg-bakery-primary text-white shadow-sm':'text-bakery-ink/55 hover:bg-white'}`}>{opt.label}</button>)}</div><div className="min-w-0 text-left sm:text-right"><p className="font-display text-xl font-bold text-bakery-primary-dark">{formatINR(totalTrend)}</p><p className={`text-xs font-semibold ${delta===null?'text-bakery-ink/45':delta>=0?'text-success':'text-error'}`}>{delta===null?'Waiting for comparison':`${delta>=0?'+':''}${delta.toFixed(1)}% vs previous data point`}</p></div></div></div>
   <div className="w-full min-w-0 overflow-hidden rounded-2xl bg-bakery-sky/35 px-2 py-3 sm:px-3 sm:py-4">{bars.length<1?<div className="flex h-52 items-center justify-center text-sm text-bakery-ink/45">Revenue data will appear here as orders come in.</div>:<><div className="relative h-52 w-full min-w-0 sm:h-60"><svg viewBox="0 0 100 84" preserveAspectRatio="none" className="block h-full w-full" role="img" aria-label={`${RANGE_OPTIONS.find(x=>x.days===range)?.label} revenue bar chart`}><path d="M 3 78 H 97" stroke="currentColor" strokeOpacity="0.12" vectorEffect="non-scaling-stroke"/><path d="M 3 56 H 97 M 3 34 H 97 M 3 12 H 97" stroke="currentColor" strokeOpacity="0.07" strokeDasharray="2 3" vectorEffect="non-scaling-stroke"/>{bars.map((b,i)=><motion.rect key={`${b.date}-${i}`} x={b.x-b.width/2} y={78-b.height} width={b.width} height={b.height} rx="1.2" className="fill-bakery-primary" initial={{y:78,height:0,opacity:0}} animate={{x:b.x-b.width/2,y:78-b.height,width:b.width,height:b.height,opacity:1}} transition={{duration:.7,ease:[.22,1,.36,1],delay:i*.035}}><title>{dateLabel(b.date)} · Revenue: {formatINR(b.revenue)} · Orders: {b.orders}</title></motion.rect>)}</svg></div><div className="mt-2 grid grid-cols-7 gap-1 px-1 text-center text-[9px] text-bakery-ink/45 sm:text-[10px]">{labelDates.map((d,i)=><span key={d.toISOString()}>{dateLabel(d)}</span>)}</div></>}</div>
  </div></motion.section>
  <div className="mt-8 grid min-w-0 gap-4 sm:grid-cols-2 lg:grid-cols-3"><Link to="/admin/orders" className="card group flex min-w-0 items-center justify-between p-5 transition-all hover:shadow-card"><div className="flex min-w-0 items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-bakery-sky text-bakery-primary"><Package className="h-5 w-5"/></div><div className="min-w-0"><p className="truncate font-display text-sm font-semibold text-bakery-ink">Manage Orders</p><p className="truncate text-xs text-bakery-ink/50">{stats?.pending_orders??0} pending to confirm</p></div></div><ArrowRight className="h-5 w-5 shrink-0 text-bakery-ink/30"/></Link><Link to="/admin/reviews" className="card group flex min-w-0 items-center justify-between p-5 transition-all hover:shadow-card"><div className="flex min-w-0 items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-accent-gold/15 text-accent-gold"><Star className="h-5 w-5"/></div><div className="min-w-0"><p className="truncate font-display text-sm font-semibold text-bakery-ink">Moderate Reviews</p><p className="truncate text-xs text-bakery-ink/50">{stats?.pending_reviews??0} awaiting approval</p></div></div><ArrowRight className="h-5 w-5 shrink-0 text-bakery-ink/30"/></Link><Link to="/admin/menu" className="card group flex min-w-0 items-center justify-between p-5 transition-all hover:shadow-card"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-bakery-sky text-bakery-primary"><TrendingUp className="h-5 w-5"/></div><div className="min-w-0"><p className="truncate font-display text-sm font-semibold text-bakery-ink">Manage Menu</p><p className="truncate text-xs text-bakery-ink/50">Add, edit & update products</p></div><ArrowRight className="h-5 w-5 shrink-0 text-bakery-ink/30"/></Link></div>
  <div className="mt-8 min-w-0"><h2 className="mb-4 font-display text-lg font-semibold text-bakery-ink">Recent Orders</h2>{(stats?.recent_orders??[]).length===0?<div className="card p-8 text-center"><Package className="mx-auto h-10 w-10 text-bakery-primary/30"/><p className="mt-3 text-sm text-bakery-ink/50">No orders yet.</p></div>:<div className="card min-w-0 divide-y divide-bakery-primary/10 overflow-hidden">{(stats?.recent_orders??[]).map(o=><Link key={o.id} to={`/orders/${o.id}`} className="flex min-w-0 items-center gap-3 p-4 transition-colors hover:bg-bakery-sky/30 sm:gap-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-bakery-sky text-bakery-primary"><Package className="h-5 w-5"/></div><div className="min-w-0 flex-1"><p className="truncate font-display text-sm font-semibold text-bakery-ink">{o.order_number}</p><p className="truncate text-xs text-bakery-ink/50">{o.customer_name} · {formatDate(o.created_at)}</p></div><p className="shrink-0 font-display text-sm font-bold text-bakery-primary-dark">{formatINR(o.total)}</p><span className={`badge hidden shrink-0 px-2.5 py-1 text-xs sm:inline-flex ${o.status==='delivered'?'bg-success/10 text-success':o.status==='cancelled'?'bg-error/10 text-error':'bg-bakery-sky text-bakery-primary'}`}>{o.status.replace(/_/g,' ')}</span></Link>)}</div>}</div>
 </div>;
}
